name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -scheme SwiftLayout -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 13 Pro' 
    - name: Run tests
      run: xcodebuild test -scheme SwiftLayout -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 13 Pro'
