name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -sdk iphoneos
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 13 Pro'
