name: SwiftLayout

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -scheme SwiftLayout -sdk iphonesimulator15.2 -destination 'name=iPhone 13 Pro'
  
  test-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -scheme SwiftLayout -sdk macosx -destination 'name=macOS'
