name: SwiftLayout

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer

jobs:
  test-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -scheme SwiftLayout-Package -sdk iphonesimulator16.0 -destination 'name=iPhone 14 Pro'
  
# test-macos:
#
#   runs-on: macos-latest
#
#   steps:
#   - uses: actions/checkout@v2
#   - name: Run tests
#     run: xcodebuild test -scheme SwiftLayout -sdk macosx -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
