name: SwiftLayout

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: tests13_1
      run: xcodebuild test -scheme SwiftLayout-Package -sdk iphonesimulator13.1 -destination 'name=iPhone 11 Pro'
    - name: tests14_1
      run: xcodebuild test -scheme SwiftLayout-Package -sdk iphonesimulator14.1 -destination 'name=iPhone 11 Pro'
    - name: tests15_2
      run: xcodebuild test -scheme SwiftLayout-Package -sdk iphonesimulator15.2 -destination 'name=iPhone 13 Pro'
  
# test-macos:
#
#   runs-on: macos-latest
#
#   steps:
#   - uses: actions/checkout@v2
#   - name: Run tests
#     run: xcodebuild test -scheme SwiftLayout -sdk macosx -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
