name: SwiftLayout

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: tests13
      run: xcodebuild test -scheme SwiftLayout-Package -sdk iphonesimulator -destination 'name=iPhone 8,platform=iOS Simulator,OS=13.7'
    - name: tests14
      run: xcod3build test -scheme SwiftLayout-Package -sdk iphonesimulator -destination 'name=iPhone 8,platform=iOS Simulator,OS=14.0'
    - name: tests15
      run: xcodebuild test -scheme SwiftLayout-Package -sdk iphonesimulator15.2 -destination 'name=iPhone 13 Pro'
  
# test-macos:
#
#   runs-on: macos-latest
#
#   steps:
#   - uses: actions/checkout@v2
#   - name: Run tests
#     run: xcodebuild test -scheme SwiftLayout -sdk macosx -destination 'platform=macOS,arch=x86_64,id=4203018E-580F-C1B5-9525-B745CECA79EB'
