name: SwiftLayout

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -scheme SwiftLayout -sdk iphonesimulator15.2 -destination 'name=iPhone 13 Pro'
